name: Github contexts
on:
    push: #push to any branch

jobs:
    print_context_values:

        runs-on: ubuntu-latest
        env:
            GITHUB_CONTEXT: ${{ toJSON(github.event) }}

        steps:
            - run: echo ${{ github.job }}
            - run: echo ${{ github.actor }}
            - run: echo ${{ github.event_name }}

            - run: echo ${{ runner.os }}
            - run: echo ${{ runner.arch }}
            - run: echo ${{ runner.os }}
            - run: echo $GITHUB_CONTEXT 

