name: .NET CI MIXED

on: 
  workflow_dispatch: {}
    
  push:
    branches: [main]
        
  pull_request:
    branches:
      [main]
 
jobs:
  build_from_matrix:

    
      name: Build release and debug versions for Ubuntu and Windows

      strategy:
        matrix:
          os: [ubuntu-latest, windows-latest]
          build-configuration: [Debug, Release]
      
      runs-on: ${{ matrix.os }}
      
      steps:
        - name: Echo Hej
          run: echo "HEJ"

        - name: Checkout code
          uses: actions/checkout@v5

        #- name: Setup .NET 9
        #  uses: actions/setup-dotnet@v5.0.0
        #  with:
        #      dotnet-version: "9.0"

        - name: Run tests
          run: dotnet test 


              
        

          
