name: .NET CI MIXED

on: 
  workflow_dispatch: {}
    
#    push:
#       branches: [main]
        
  pull_request:
    branches:
      [main]
 
jobs:
  echo_hej:
      name: Echo Hej
      runs-on: ubuntu-latest
      
      steps:
            - run: echo "HEJ"
