name: .NET CI MIXED

on: 
  workflow_dispatch: {}
      
  pull_request:
    branches:
      [main]
 
jobs:
  test_from_matrix:
  
      name: Run tests for Ubuntu and Windows

      strategy:
        matrix:
          os: [ubuntu-latest, windows-latest]
          build-configuration: [Debug, Release]
      
      runs-on: ${{ matrix.os }}
      
      steps:
        - name: Echo Hej
          run: echo "HEJ"

        - name: Checkout code
          uses: actions/checkout@v5

        - name: Build projects
          run: dotnet build

        - name: Run tests
          run: dotnet test

  build-debug-and-relase:

    name: Build Debug and Release for Ubuntu and Windows

    strategy:
        matrix:
          os: [ubuntu-latest, windows-latest]
          build-configuration: [Debug, Release]

    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v5
      - run: dotnet build --configuration ${{ matrix.build-configuration}}
        
      

      





              
        

          
